"""empty message

Revision ID: 103c5b091471
Revises: 
Create Date: 2018-07-30 11:01:32.687732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103c5b091471'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_ref', sa.String(length=60), nullable=True),
    sa.Column('aplikasi_id', sa.Integer(), nullable=True),
    sa.Column('kamar', sa.String(length=60), nullable=True),
    sa.Column('nasabah', sa.String(length=60), nullable=True),
    sa.Column('check_in_date', sa.String(length=60), nullable=True),
    sa.Column('check_out_date', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=True),
    sa.Column('penghasilan', sa.Integer(), nullable=True),
    sa.Column('pengeluaran', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['aplikasi_id'], ['aplikasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
